### PR TITLE
Don't crash on non existent pastes / File::Spec / general cleanup

### PR DESCRIPTION
**Pull request by stephan48**

### CODE REVIEW

**Comment by jhthorsen** [comment]
I can't taket this pull request without a test. I also think it should rather be something like this:

    my $paste = File::Spec->catfile($paste_dir, $paste_id);
    return $c->reply->not_found unless -e $paste;
    return $self->render(content => decode "UTF-8", slurp $paste);

To be honest, I don't really get my original code either. I can implement the change, unless you update the PR.

**Comment by stephan48** [comment]
Would it make sense to reevaluate all the cases I fixed in my commits?

**Comment by jhthorsen** [comment]
I think I have "converted" your commits now. Let me know if I'm wrong. Some more comments:

* There's no reason to use SHA1 for making unique files
* The controller object should be called $c in a Mojolicious::Lite app

Also, please rebase and push again next time. It's difficult to read the different commits when they append to previous commits in the same PR.

**Comment by jhthorsen** [comment]
Closing this, since I don't believe there are any open issues.

**Pull request closed without merging**
